### ISSUE TITLE
Issue with cross domain

### ISSUE THREAD

**Issue by zhengsk** [claviska/jquery-minicolors#226]
Bug when in iframe.

https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.js#L978

>  // Handle events
>   $([document, **top.document**])
>     // Hide on clicks outside of the control
>     .on('mousedown.minicolors touchstart.minicolors', function(event) {
>       if(!$(event.target).parents().add(event.target).hasClass('minicolors')) {
>         hide();
>       }
>     })

**Comment by claviska** [comment]
Hi there, thanks for the report. Unfortunately, this isn't enough to verify the bug or accept a patch. Can you answer a couple questions?

- How are you instantiating the plugin? (e.g. is the target element in the iframe or is the plugin being loaded in an iframe?)
- Can you provide a minimal test case demonstrating the issue?

Thanks!

**Comment by zhengsk** [comment]
Hi, the plugin being loaded in an iframe.
For example: 
page_a.html is the domain `www.a.com`
page_b.html is the domain `www.b.com`

page_a.html has an element `iframe` and iframe's `src` attribute is `page_b.html`.
The plugin loaded in `page_b.html'. 
So page_a.html and page_b.html is not in the same domain.

But plugin in page_b.html and because of the [code](https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.js#L978)

`$([document, **top.document**])` in plugin. jQuery bind event cross domain will throw error.

Hope my express clearly.
Thank you for your great plugin, i like jquery-minicolors!

**Comment by markvantilburg** [comment]
I'm wondering is it actually needed to close when they click 'outside' of a frame?

**Comment by claviska** [comment]
Agree, I think this is an edge case and should probably be handled through a custom listener. Unfortunately, there isn't a `show` or `hide` method yet so that can't be done programmatically. You can probably blur the input for now to make it disappear.

I also don't think we can guarantee that `top.document` will be the correct document in all cases. I think the proper solution is to add a method for `hide` and a matching one for `show`.

**Comment by dmaicher** [comment]
Any update on this one? I'm also affected by it :cry: 

```
jquery.minicolors.js:978 Uncaught DOMException: Blocked a frame with origin "http://xxx.dev" from accessing a cross-origin frame.
```

**Comment by claviska** [comment]
Resolved in #231

**Comment by kolosovskiy** [comment]
I am still experiencing this error.

Version: 2.2.6

I have installed minicolors via npm.
